const samplesData = [
  {
    address: "223 8th Ave. New York, NY 10011",
    category: "Highly Walkable",
    categoryRank: "1",
    greenNear: "55",
    yellowFarther: "7",
    redDistant: "12",
    walkabilityScore: "20",
    streetView: "streetview-8th-ave-new-york.2.png",
  },
  {
    address: "Sarphatipark 38I, 1072 PB Amsterdam, Netherlands",
    category: "Highly Walkable",
    categoryRank: "2",
    greenNear: "52",
    yellowFarther: "7",
    redDistant: "15",
    walkabilityScore: "23",
    streetView: "streetview-amsterdam.1.jpg",
  },
  {
    address: "1902 2nd Ave, Seattle, WA 98101",
    category: "Highly Walkable",
    categoryRank: "3",
    greenNear: "49",
    yellowFarther: "13",
    redDistant: "12",
    walkabilityScore: "20",
    streetView: "streetview-seattle-wa.1.png",
  },
  {
    address: "29 S La Salle St, Chicago, IL 60603",
    category: "Highly Walkable",
    categoryRank: "4",
    greenNear: "49",
    yellowFarther: "11",
    redDistant: "14",
    walkabilityScore: "25",
    streetView: "streetview-chicago-il.1.png",
  },
  {
    address: "313 Sauchiehall St. Glasgow G2 3JA Scotland",
    category: "Highly Walkable",
    categoryRank: "5",
    greenNear: "49",
    yellowFarther: "11",
    redDistant: "14",
    walkabilityScore: "23",
    streetView: "streetview-glasgow-scotland.1.png",
  },
  {
    address: "18 Whitechapel, Liverpool L1 6DS, UK",
    category: "Highly Walkable",
    categoryRank: "6",
    greenNear: "49",
    yellowFarther: "9",
    redDistant: "16",
    walkabilityScore: "27",
    streetView: "streetview-liverpool-uk.1.png",
  },
  {
    address: "10 Lorne St, Te Aro, Wellington 6011, New Zealand",
    category: "Highly Walkable",
    categoryRank: "7",
    greenNear: "49",
    yellowFarther: "7",
    redDistant: "18",
    walkabilityScore: "20",
    streetView: "streetview-wellington-new-zealand.1.png",
  },
  {
    address: "41 E Hastings St, Vancouver, BC V6A 1M9, Canada",
    category: "Highly Walkable",
    categoryRank: "8",
    greenNear: "48",
    yellowFarther: "12",
    redDistant: "14",
    walkabilityScore: "19",
    streetView: "streetview-vancouver-canada.1.png",
  },
  {
    address: "10 Rue de Rivoli, 75004 Paris, France",
    category: "Highly Walkable",
    categoryRank: "9",
    greenNear: "48",
    yellowFarther: "8",
    redDistant: "18",
    walkabilityScore: "24",
    streetView: "streetview-paris-france.1.png",
  },
  {
    address: "67A Regent Rd, Cape Town, 8005, South Africa",
    category: "Highly Walkable",
    categoryRank: "10",
    greenNear: "48",
    yellowFarther: "2",
    redDistant: "24",
    walkabilityScore: "23",
  },
  {
    address: "301 Market St, Philadelphia, PA 19106",
    category: "Somewhat Walkable",
    categoryRank: "1",
    greenNear: "47",
    yellowFarther: "4",
    redDistant: "23",
    walkabilityScore: "19",
    streetView: "streetview-philadelphia-pa.1.png",
  },
  {
    address: "163 Lai Chi Kok Rd, Tai Kok Tsui, Hong Kong",
    category: "Somewhat Walkable",
    categoryRank: "2",
    greenNear: "45",
    yellowFarther: "10",
    redDistant: "19",
    walkabilityScore: "20",
    streetView: "streetview-kok-tsui-hong-kong.1.png",
  },
  {
    address: "55 Triq San Vincenz, Tas-Sliema, Malta",
    category: "Somewhat Walkable",
    categoryRank: "3",
    greenNear: "45",
    yellowFarther: "9",
    redDistant: "20",
    walkabilityScore: "15",
    streetView: "streetview-malta.1.png",
  },
  {
    address: "618-622 Anacapa St, Santa Barbara, CA 93101",
    category: "Somewhat Walkable",
    categoryRank: "4",
    greenNear: "45",
    yellowFarther: "7",
    redDistant: "22",
    walkabilityScore: "22",
    streetView: "streetview-santa-barbara-ca.1.png",
  },
  {
    address: "50 Grand Parade, Centre, Cork, T12 D638, Ireland",
    category: "Somewhat Walkable",
    categoryRank: "5",
    greenNear: "44",
    yellowFarther: "13",
    redDistant: "17",
    walkabilityScore: "17",
    streetView: "streetview-cork-ireland.1.png",
  },
  {
    address: "107 Patton Ave, Asheville, NC 28801",
    category: "Somewhat Walkable",
    categoryRank: "6",
    greenNear: "44",
    yellowFarther: "10",
    redDistant: "20",
    walkabilityScore: "18",
    streetView: "streetview-ashville-nc.1.png",
  },
  {
    address: "316 King St, Charleston, SC 29401",
    category: "Somewhat Walkable",
    categoryRank: "7",
    greenNear: "44",
    yellowFarther: "8",
    redDistant: "22",
    walkabilityScore: "19",
    streetView: "streetview-charleston-nc.1.png",
  },
  {
    address: "Gabriel-Max-Straße 15, 10245 Berlin, Germany",
    category: "Somewhat Walkable",
    categoryRank: "8",
    greenNear: "42",
    yellowFarther: "14",
    redDistant: "18",
    walkabilityScore: "19",
    streetView: "streetview-berlin-germany.1.png",
  },
  {
    address: "R. Alexandre Martins, 96 - SP, 11025-200, Brazil",
    category: "Somewhat Walkable",
    categoryRank: "9",
    greenNear: "42",
    yellowFarther: "11",
    redDistant: "21",
    walkabilityScore: "21",
    streetView: "streetview-brazil.1.png",
  },
  {
    address: "245 Granby St, Norfolk, VA 23510",
    category: "Somewhat Walkable",
    categoryRank: "10",
    greenNear: "42",
    yellowFarther: "9",
    redDistant: "23",
    walkabilityScore: "21",
    streetView: "streetview-norfolk-va.1.png",
  },
  {
    address: "14 E Washington St, Indianapolis, IN 46204",
    category: "Somewhat Walkable",
    categoryRank: "11",
    greenNear: "42",
    yellowFarther: "7",
    redDistant: "25",
    walkabilityScore: "22",
    streetView: "streetview-indianapolis-in.1.png",
  },
  {
    address: "1030 Tiverton Ave. Los Angeles, CA 90024",
    category: "Somewhat Walkable",
    categoryRank: "12",
    greenNear: "41",
    yellowFarther: "17",
    redDistant: "16",
    walkabilityScore: "25",
    streetView: "streetview-los-angeles-ca.1.png",
  },
  {
    address: "1900 Broadway, Boulder, CO 80302",
    category: "Somewhat Walkable",
    categoryRank: "13",
    greenNear: "40",
    yellowFarther: "15",
    redDistant: "19",
    walkabilityScore: "23",
    streetView: "streetview-boulder-co.1.png",
  },
  {
    address: "526 Superior Ave, Cleveland, OH 44114",
    category: "Somewhat Walkable",
    categoryRank: "14",
    greenNear: "40",
    yellowFarther: "9",
    redDistant: "25",
    walkabilityScore: "21",
    streetView: "streetview-cleveland-oh.1.png",
  },
  {
    address: "1505 Ponce de Leon, Coral Gables, FL 33134",
    category: "Less Walkable",
    categoryRank: "1",
    greenNear: "38",
    yellowFarther: "7",
    redDistant: "29",
    walkabilityScore: "23",
    streetView: "streetview-coral-gables-fl.1.png",
  },
  {
    address: "4100 Georgia Ave NW, Washington, DC 20011",
    category: "Less Walkable",
    categoryRank: "2",
    greenNear: "37",
    yellowFarther: "10",
    redDistant: "27",
    walkabilityScore: "22",
    streetView: "streetview-washington-dc.1.png",
  },
  {
    address: "555 Church St. Nashville, TN 37203",
    category: "Less Walkable",
    categoryRank: "3",
    greenNear: "37",
    yellowFarther: "8",
    redDistant: "29",
    walkabilityScore: "24",
  },
  {
    address: "332 E William St. Ann Arbor, MI 48104",
    category: "Less Walkable",
    categoryRank: "4",
    greenNear: "36",
    yellowFarther: "17",
    redDistant: "21",
    walkabilityScore: "27",
  },
  {
    address: "6485 Victoria Ave, Montreal, QC H3W, Canada",
    category: "Less Walkable",
    categoryRank: "5",
    greenNear: "36",
    yellowFarther: "8",
    redDistant: "30",
    walkabilityScore: "21",
  },
  {
    address: "107 High St, Charlestown, MA 02129",
    category: "Less Walkable",
    categoryRank: "6",
    greenNear: "36",
    yellowFarther: "8",
    redDistant: "30",
    walkabilityScore: "17",
  },
  {
    address: "201 Chartres St, New Orleans, LA 70130",
    category: "Less Walkable",
    categoryRank: "7",
    greenNear: "35",
    yellowFarther: "16",
    redDistant: "23",
    walkabilityScore: "21",
  },
  {
    address: "2 Junction Road, Archway, London N19 5FF",
    category: "Less Walkable",
    categoryRank: "8",
    greenNear: "34",
    yellowFarther: "9",
    redDistant: "31",
    walkabilityScore: "24",
  },
  {
    address: "1431 SW Park Ave. Portland, OR 97201",
    category: "Less Walkable",
    categoryRank: "9",
    greenNear: "33",
    yellowFarther: "21",
    redDistant: "20",
    walkabilityScore: "21",
  },
  {
    address: "1080 Peachtree St NE, Atlanta, GA 30309",
    category: "Less Walkable",
    categoryRank: "10",
    greenNear: "32",
    yellowFarther: "19",
    redDistant: "23",
    walkabilityScore: "23",
  },
  {
    address: "2033 Broadway, Nashville, TN 37203",
    category: "Less Walkable",
    categoryRank: "11",
    greenNear: "27",
    yellowFarther: "17",
    redDistant: "30",
    walkabilityScore: "22",
  },
  {
    address: "2525 Ocean Ave, San Francisco, CA 94132",
    category: "Less Walkable",
    categoryRank: "12",
    greenNear: "27",
    yellowFarther: "15",
    redDistant: "32",
    walkabilityScore: "21",
  },
  {
    address: "5025 Penn Ave, Pittsburgh, PA 15224",
    category: "Less Walkable",
    categoryRank: "13",
    greenNear: "23",
    yellowFarther: "5",
    redDistant: "46",
    walkabilityScore: "18",
    streetView: "streetview-pittsburgh-pa.1.png",
  },
  {
    address: "1015 Elvira Ave. Nashville, TN 37216",
    category: "Less Walkable",
    categoryRank: "14",
    greenNear: "12",
    yellowFarther: "13",
    redDistant: "49",
    walkabilityScore: "12",
  },
];

export default samplesData;
