const samplesData = [
  {
    address: "223 8th Ave. New York, NY 10011",
    category: "Highly Walkable",
    categoryRank: "1",
    greenNear: "55",
    yellowFarther: "7",
    redDistant: "12",
    walkabilityScore: "20",
    streetView: "streetview-8th-ave-new-york.3.jpg",
    aerialCloseUp: "aerial-close-up-233-8th-ave-new-york.3.jpg",
    aerialMidRange: "aerial-mid-range-233-8th-ave-new-york.3.jpg",
    aerialDistant: "aerial-distant-233-8th-ave-new-york.3.jpg",
  },
  {
    address: "Sarphatipark 38I, 1072 PB Amsterdam, Netherlands",
    category: "Highly Walkable",
    categoryRank: "2",
    greenNear: "52",
    yellowFarther: "7",
    redDistant: "15",
    walkabilityScore: "23",
    streetView: "streetview-amsterdam.3.jpg",
    aerialCloseUp: "aerial-close-up-sarphatipark-38i-amsterdam.3.jpg",
    aerialMidRange: "aerial-mid-range-sarphatipark-38i-amsterdam.3.jpg",
    aerialDistant: "aerial-distant-sarphatipark-38i-amsterdam.3.jpg",
  },
  {
    address: "1902 2nd Ave, Seattle, WA 98101",
    category: "Highly Walkable",
    categoryRank: "3",
    greenNear: "49",
    yellowFarther: "13",
    redDistant: "12",
    walkabilityScore: "20",
    streetView: "streetview-seattle-wa.3.jpg",
    aerialCloseUp: "aerial-close-up-1902-2nd-ave-seattle-wa.3.jpg",
    aerialMidRange: "aerial-mid-range-1902-2nd-ave-seattle-wa.3.jpg",
    aerialDistant: "aerial-distant-1902-2nd-ave-seattle-wa.3.jpg",
  },
  {
    address: "29 S La Salle St, Chicago, IL 60603",
    category: "Highly Walkable",
    categoryRank: "4",
    greenNear: "49",
    yellowFarther: "11",
    redDistant: "14",
    walkabilityScore: "25",
    streetView: "streetview-chicago-il.3.jpg",
    aerialCloseUp: "aerial-close-up-la-salle-st-chicago.3.jpg",
    aerialMidRange: "aerial-mid-range-la-salle-st-chicago.3.jpg",
    aerialDistant: "aerial-distant-la-salle-st-chicago.3.jpg",
  },
  {
    address: "313 Sauchiehall St. Glasgow G2 3JA Scotland",
    category: "Highly Walkable",
    categoryRank: "5",
    greenNear: "49",
    yellowFarther: "11",
    redDistant: "14",
    walkabilityScore: "23",
    streetView: "streetview-glasgow-scotland.3.jpg",
    aerialCloseUp: "aerial-close-up-glasgow-scotland.3.jpg",
    aerialMidRange: "aerial-mid-range-glasgow-scotland.3.jpg",
    aerialDistant: "aerial-distant-la-glasgow-scotland.3.jpg",
  },
  {
    address: "18 Whitechapel, Liverpool L1 6DS, UK",
    category: "Highly Walkable",
    categoryRank: "6",
    greenNear: "49",
    yellowFarther: "9",
    redDistant: "16",
    walkabilityScore: "27",
    streetView: "streetview-liverpool-uk.3.jpg",
    aerialCloseUp: "aerial-close-up-liverpool-uk.3.jpg",
    aerialMidRange: "aerial-mid-range-liverpool-uk.3.jpg",
    aerialDistant: "aerial-distant-liverpool-uk.3.jpg",
  },
  {
    address: "10 Lorne St, Te Aro, Wellington 6011, New Zealand",
    category: "Highly Walkable",
    categoryRank: "7",
    greenNear: "49",
    yellowFarther: "7",
    redDistant: "18",
    walkabilityScore: "20",
    streetView: "streetview-wellington-new-zealand.3.jpg",
    aerialCloseUp: "aerial-close-up-new-zealand.3.1.jpg",
    aerialMidRange: "aerial-mid-range-new-zealand.3.1.jpg",
    aerialDistant: "aerial-distant-new-zealand.3.1.jpg",
  },
  {
    address: "41 E Hastings St, Vancouver, BC V6A 1M9, Canada",
    category: "Highly Walkable",
    categoryRank: "8",
    greenNear: "48",
    yellowFarther: "12",
    redDistant: "14",
    walkabilityScore: "19",
    streetView: "streetview-vancouver-canada.3.jpg",
    aerialCloseUp: "aerial-close-up-vancouver-canada.3.1.jpg",
    aerialMidRange: "aerial-mid-range-vancouver-canada.3.1.jpg",
    aerialDistant: "aerial-distant-vancouver-canada.3.1.jpg",
  },
  {
    address: "10 Rue de Rivoli, 75004 Paris, France",
    category: "Highly Walkable",
    categoryRank: "9",
    greenNear: "48",
    yellowFarther: "8",
    redDistant: "18",
    walkabilityScore: "24",
    streetView: "streetview-paris-france.3.jpg",
    aerialCloseUp: "aerial-close-up-paris-france.3.jpg",
    aerialMidRange: "aerial-mid-range-paris-france.3.jpg",
    aerialDistant: "aerial-distant-paris-france.3.jpg",
  },
  {
    address: "67A Regent Rd, Cape Town, 8005, South Africa",
    category: "Highly Walkable",
    categoryRank: "10",
    greenNear: "48",
    yellowFarther: "2",
    redDistant: "24",
    walkabilityScore: "23",
    streetView: "streetview-cape-town-sa.3.jpg",
    aerialCloseUp: "aerial-close-up-cape-town-south-africa.3.1.jpg",
    aerialMidRange: "aerial-mid-range-cape-town-south-africa.3.1.jpg",
    aerialDistant: "aerial-distant-cape-town-south-africa.3.2.jpg",
  },
  {
    address: "301 Market St, Philadelphia, PA 19106",
    category: "Somewhat Walkable",
    categoryRank: "1",
    greenNear: "47",
    yellowFarther: "4",
    redDistant: "23",
    walkabilityScore: "19",
    streetView: "streetview-philadelphia-pa.3.1.jpg",
    aerialCloseUp: "aerial-close-up-market-st-philadelphia-pa.3.1.jpg",
    aerialMidRange: "aerial-mid-range-market-st-philadelphia-pa.3.1.jpg",
    aerialDistant: "aerial-distant-market-st-philadelphia-pa.3.1.jpg",
  },
  {
    address: "163 Lai Chi Kok Rd, Tai Kok Tsui, Hong Kong",
    category: "Somewhat Walkable",
    categoryRank: "2",
    greenNear: "45",
    yellowFarther: "10",
    redDistant: "19",
    walkabilityScore: "20",
    streetView: "streetview-tai-kok-tsui-hong-kong.3.1.jpg",
    aerialCloseUp: "aerial-close-up-tai-kok-tsui-hong-kong.3.jpg",
    aerialMidRange: "aerial-mid-range-tai-kok-tsui-hong-kong.3.jpg",
    aerialDistant: "aerial-distant-tai-kok-tsui-hong-kong.3.jpg",
  },
  {
    address: "55 Triq San Vincenz, Tas-Sliema, Malta",
    category: "Somewhat Walkable",
    categoryRank: "3",
    greenNear: "45",
    yellowFarther: "9",
    redDistant: "20",
    walkabilityScore: "15",
    streetView: "streetview-malta.3.1.jpg",
    aerialCloseUp: "aerial-close-up-malta.3.1.jpg",
    aerialMidRange: "aerial-mid-range-malta.3.1.jpg",
    aerialDistant: "aerial-distant-malta.3.1.jpg",
  },
  {
    address: "618-622 Anacapa St, Santa Barbara, CA 93101",
    category: "Somewhat Walkable",
    categoryRank: "4",
    greenNear: "45",
    yellowFarther: "7",
    redDistant: "22",
    walkabilityScore: "22",
    streetView: "streetview-santa-barbara-ca.3.1.jpg",
    aerialCloseUp: "aerial-close-up-santa-barbara-ca.3.1.jpg",
    aerialMidRange: "aerial-mid-range-santa-barbara-ca.3.1.jpg",
    aerialDistant: "aerial-distant-santa-barbara-ca.3.1.jpg",
  },
  {
    address: "50 Grand Parade, Centre, Cork, T12 D638, Ireland",
    category: "Somewhat Walkable",
    categoryRank: "5",
    greenNear: "44",
    yellowFarther: "13",
    redDistant: "17",
    walkabilityScore: "17",
    streetView: "streetview-cork-ireland.3.1.jpg",
    aerialCloseUp: "aerial-close-up-cork-ireland.3.jpg",
    aerialMidRange: "aerial-mid-range-cork-ireland.3.jpg",
    aerialDistant: "aerial-distant-cork-ireland.3.jpg",
  },
  {
    address: "107 Patton Ave, Asheville, NC 28801",
    category: "Somewhat Walkable",
    categoryRank: "6",
    greenNear: "44",
    yellowFarther: "10",
    redDistant: "20",
    walkabilityScore: "18",
    streetView: "streetview-ashville-nc.3.1.jpg",
    aerialCloseUp: "aerial-close-up-ashville-nc.3.jpg",
    aerialMidRange: "aerial-mid-range-ashville-nc.3.jpg",
    aerialDistant: "aerial-distant-ashville-nc.3.jpg",
  },
  {
    address: "316 King St, Charleston, SC 29401",
    category: "Somewhat Walkable",
    categoryRank: "7",
    greenNear: "44",
    yellowFarther: "8",
    redDistant: "22",
    walkabilityScore: "19",
    streetView: "streetview-charleston-sc.3.jpg",
    aerialCloseUp: "aerial-close-up-charleston-sc.3.jpg",
    aerialMidRange: "aerial-mid-range-charleston-sc.3.jpg",
    aerialDistant: "aerial-distant-charleston-sc.3.jpg",
  },
  {
    address: "Gabriel-Max-Straße 15, 10245 Berlin, Germany",
    category: "Somewhat Walkable",
    categoryRank: "8",
    greenNear: "42",
    yellowFarther: "14",
    redDistant: "18",
    walkabilityScore: "19",
    streetView: "streetview-berlin-germany.3.jpg",
    aerialCloseUp: "aerial-close-up-berlin-germany.3.jpg",
    aerialMidRange: "aerial-mid-range-berlin-germany.3.jpg",
    aerialDistant: "aerial-distant-berlin-germany.3.jpg",
  },
  {
    address: "R. Alexandre Martins, 96 - SP, 11025-200, Brazil",
    category: "Somewhat Walkable",
    categoryRank: "9",
    greenNear: "42",
    yellowFarther: "11",
    redDistant: "21",
    walkabilityScore: "21",
    streetView: "streetview-brazil.3.jpg",
    aerialCloseUp: "aerial-close-up-sp-brazil.3.jpg",
    aerialMidRange: "aerial-mid-range-sp-brazil.3.jpg",
    aerialDistant: "aerial-distant-sp-brazil.3.jpg",
  },
  {
    address: "245 Granby St, Norfolk, VA 23510",
    category: "Somewhat Walkable",
    categoryRank: "10",
    greenNear: "42",
    yellowFarther: "9",
    redDistant: "23",
    walkabilityScore: "21",
    streetView: "streetview-norfolk-va.3.jpg",
    aerialCloseUp: "aerial-close-up-norfolk-va.3.1.jpg",
    aerialMidRange: "aerial-mid-range-norfolk-va.3.1.jpg",
    aerialDistant: "aerial-distant-norfolk-va.3.1.jpg",
  },
  {
    address: "14 E Washington St, Indianapolis, IN 46204",
    category: "Somewhat Walkable",
    categoryRank: "11",
    greenNear: "42",
    yellowFarther: "7",
    redDistant: "25",
    walkabilityScore: "22",
    streetView: "streetview-washington-st-indianapolis.in.3.jpg",
    aerialCloseUp: "aerial-close-up-indianapolis-in.3.jpg",
    aerialMidRange: "aerial-mid-range-indianapolis-in.3.jpg",
    aerialDistant: "aerial-distant-indianapolis-in.3.jpg",
  },
  {
    address: "1030 Tiverton Ave. Los Angeles, CA 90024",
    category: "Somewhat Walkable",
    categoryRank: "12",
    greenNear: "41",
    yellowFarther: "17",
    redDistant: "16",
    walkabilityScore: "25",
    streetView: "streetview-los-angeles-ca.3.1.jpg",
    aerialCloseUp: "aerial-close-up-los-angeles-ca.3.1.jpg",
    aerialMidRange: "aerial-mid-range-los-angeles-ca.3.1.jpg",
    aerialDistant: "aerial-distant-los-angeles-ca.3.1.jpg",
  },
  {
    address: "1900 Broadway, Boulder, CO 80302",
    category: "Somewhat Walkable",
    categoryRank: "13",
    greenNear: "40",
    yellowFarther: "15",
    redDistant: "19",
    walkabilityScore: "23",
    streetView: "streetview-boulder-co.3.jpg",
    aerialCloseUp: "aerial-close-up-boulder-co.3.jpg",
    aerialMidRange: "aerial-mid-range-boulder-co.3.jpg",
    aerialDistant: "aerial-distant-boulder-co.3.jpg",
  },
  {
    address: "526 Superior Ave, Cleveland, OH 44114",
    category: "Somewhat Walkable",
    categoryRank: "14",
    greenNear: "40",
    yellowFarther: "9",
    redDistant: "25",
    walkabilityScore: "21",
    streetView: "streetview-cleveland-oh.3.jpg",
    aerialCloseUp: "aerial-close-up-superior-ave-cleveland-oh.3.jpg",
    aerialMidRange: "aerial-mid-range-superior-ave-cleveland-oh.3.jpg",
    aerialDistant: "aerial-distant-superior-ave-cleveland-oh.3.jpg",
  },
  {
    address: "1505 Ponce de Leon, Coral Gables, FL 33134",
    category: "Less Walkable",
    categoryRank: "1",
    greenNear: "38",
    yellowFarther: "7",
    redDistant: "29",
    walkabilityScore: "23",
    streetView: "streetview-coral-gables-fl.3.png",
    aerialCloseUp: "aerial-close-up-coral-gables-fl.2.jpg",
    aerialMidRange: "aerial-mid-range-coral-gables-fl.2.jpg",
    aerialDistant: "aerial-distant-coral-gables-fl.2.jpg",
  },
  {
    address: "4100 Georgia Ave NW, Washington, DC 20011",
    category: "Less Walkable",
    categoryRank: "2",
    greenNear: "37",
    yellowFarther: "10",
    redDistant: "27",
    walkabilityScore: "22",
    streetView: "streetview-washington-dc.3.png",
    aerialCloseUp: "aerial-close-up-georgia-ave-nw-washington-dc.3.jpg",
    aerialMidRange: "aerial-mid-range-georgia-ave-nw-washington-dc.3.jpg",
    aerialDistant: "aerial-distant-georgia-ave-nw-washington-dc.3.jpg",
  },
  {
    address: "555 Church St. Nashville, TN 37203",
    category: "Less Walkable",
    categoryRank: "3",
    greenNear: "37",
    yellowFarther: "8",
    redDistant: "29",
    walkabilityScore: "24",
    streetView: "streetview-church-st-nashville-tn.3.png",
    aerialCloseUp: "aerial-close-up-church-st-nashville-tn.2.jpg",
    aerialMidRange: "aerial-mid-range-church-st-nashville-tn.2.jpg",
    aerialDistant: "aerial-distant-church-st-nashville-tn.2.jpg",
  },
  {
    address: "332 E William St. Ann Arbor, MI 48104",
    category: "Less Walkable",
    categoryRank: "4",
    greenNear: "36",
    yellowFarther: "17",
    redDistant: "21",
    walkabilityScore: "27",
    streetView: "streetview-ann-arbor-mi.3.png",
    aerialCloseUp: "aerial-close-up-ann-arbor-mi.2.jpg",
    aerialMidRange: "aerial-mid-range-ann-arbor-mi.2.jpg",
    aerialDistant: "aerial-distant-ann-arbor-mi.2.jpg",
  },
  {
    address: "6485 Victoria Ave, Montreal, QC H3W, Canada",
    category: "Less Walkable",
    categoryRank: "5",
    greenNear: "36",
    yellowFarther: "8",
    redDistant: "30",
    walkabilityScore: "21",
    streetView: "streetview-montreal-canada.3.png",
    aerialCloseUp: "aerial-close-up-montreal-canada.3.jpg",
    aerialMidRange: "aerial-mid-range-montreal-canada.3.jpg",
    aerialDistant: "aerial-distant-montreal-canada.3.jpg",
  },
  {
    address: "107 High St, Charlestown, MA 02129",
    category: "Less Walkable",
    categoryRank: "6",
    greenNear: "36",
    yellowFarther: "8",
    redDistant: "30",
    walkabilityScore: "17",
    streetView: "streetview-charlestown-massachusetts.3.png",
    aerialCloseUp: "aerial-close-up-charlestown-ma.2.jpg",
    aerialMidRange: "aerial-mid-range-charlestown-ma.2.jpg",
    aerialDistant: "aerial-distant-charlestown-ma.2.jpg",
  },
  {
    address: "201 Chartres St, New Orleans, LA 70130",
    category: "Less Walkable",
    categoryRank: "7",
    greenNear: "35",
    yellowFarther: "16",
    redDistant: "23",
    walkabilityScore: "21",
    streetView: "streetview-chartres-st-new-orleans.3.png",
    aerialCloseUp: "aerial-close-up-new-orleans-la.3.jpg",
    aerialMidRange: "aerial-mid-range-new-orleans-la.3.jpg",
    aerialDistant: "aerial-distant-new-orleans-la.3.jpg",
  },
  {
    address: "2 Junction Road, Archway, London N19 5FF",
    category: "Less Walkable",
    categoryRank: "8",
    greenNear: "34",
    yellowFarther: "9",
    redDistant: "31",
    walkabilityScore: "24",
    streetView: "streetview-archway-london-uk.3.png",
    aerialCloseUp: "aerial-close-up-archway-london-uk.2.jpg",
    aerialMidRange: "aerial-mid-range-archway-london-uk.2.jpg",
    aerialDistant: "aerial-distant-archway-london-uk.2.jpg",
  },
  {
    address: "1431 SW Park Ave. Portland, OR 97201",
    category: "Less Walkable",
    categoryRank: "9",
    greenNear: "33",
    yellowFarther: "21",
    redDistant: "20",
    walkabilityScore: "21",
    streetView: "streetview-portland-or.3.png",
    aerialCloseUp: "aerial-close-up-park-ave-portland-or.3.jpg",
    aerialMidRange: "aerial-mid-range-park-ave-portland-or.3.jpg",
    aerialDistant: "aerial-distant-park-ave-portland-or.3.jpg",
  },
  {
    address: "1080 Peachtree St NE, Atlanta, GA 30309",
    category: "Less Walkable",
    categoryRank: "10",
    greenNear: "32",
    yellowFarther: "19",
    redDistant: "23",
    walkabilityScore: "23",
    streetView: "streetview-peachtree-atlanta-ga.3.png",
    aerialCloseUp: "aerial-close-up-peachtree-st-ne-atlanta-ga.3.jpg",
    aerialMidRange: "aerial-mid-range-peachtree-st-ne-atlanta-ga.3.jpg",
    aerialDistant: "aerial-distant-peachtree-st-ne-atlanta-ga.3.jpg",
  },
  {
    address: "2033 Broadway, Nashville, TN 37203",
    category: "Less Walkable",
    categoryRank: "11",
    greenNear: "27",
    yellowFarther: "17",
    redDistant: "30",
    walkabilityScore: "22",
    streetView: "streetview-broadway-nashville-tn.3.png",
    aerialCloseUp: "aerial-close-up-broadway-nashville-tn.2.jpg",
    aerialMidRange: "aerial-mid-range-broadway-nashville-tn.2.jpg",
    aerialDistant: "aerial-distant-broadway-nashville-tn.2.jpg",
  },
  {
    address: "2525 Ocean Ave, San Francisco, CA 94132",
    category: "Less Walkable",
    categoryRank: "12",
    greenNear: "27",
    yellowFarther: "15",
    redDistant: "32",
    walkabilityScore: "21",
    streetView: "streetview-ocean-ave-san-francisco-ca.3.png",
    aerialCloseUp: "aerial-close-up-ocean-ave-san-francisco-ca.3.jpg",
    aerialMidRange: "aerial-mid-range-ocean-ave-san-francisco-ca.3.jpg",
    aerialDistant: "aerial-distant-ocean-ave-san-francisco-ca.3.jpg",
  },
  {
    address: "5025 Penn Ave, Pittsburgh, PA 15224",
    category: "Less Walkable",
    categoryRank: "13",
    greenNear: "23",
    yellowFarther: "5",
    redDistant: "46",
    walkabilityScore: "18",
    streetView: "streetview-pittsburgh-pa.3.png",
    aerialCloseUp: "aerial-close-up-penn-ave-pittsburgh-pa.3.jpg",
    aerialMidRange: "aerial-mid-range-penn-ave-pittsburgh-pa.3.jpg",
    aerialDistant: "aerial-distant-penn-ave-pittsburgh-pa.3.jpg",
  },
  {
    address: "1015 Elvira Ave. Nashville, TN 37216",
    category: "Less Walkable",
    categoryRank: "14",
    greenNear: "12",
    yellowFarther: "13",
    redDistant: "49",
    walkabilityScore: "12",
    streetView: "streetview-elvira-ave-nashville-tn.3.png",
    aerialCloseUp: "aerial-close-up-elvira-ave-nashville.tn.2.jpg",
    aerialMidRange: "aerial-mid-range-elvira-ave-nashville.tn.2.jpg",
    aerialDistant: "aerial-distant-elvira-ave-nashville.tn.2.jpg",
  },
];

export default samplesData;
